.travis.yml
check-links.sh
check-paths.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rurust/rust-by-example-ru/15)

Добавляем htmlproofer в .travis.yml

---

Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rurust/rust-by-example-ru/19)

Чиним сборку

---

check-links.sh

Fix #16
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rurust/rust-by-example-ru/26)

Удаляем "12.8.1 Testcase: unit clarification" из исключений

---

deploy.sh

Fix #10
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rurust/rust-by-example-ru/27)

Пробуем исправить подсветку синтаксиса в примерах

---

examples/custom_types/enum/testcase_linked_list/input.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rurust/rust-by-example-ru/28)

микро правка по переводу "and" на "и"

---

examples/flow_control/match/destructuring/destructure_pointers/input.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rurust/rust-by-example-ru/29)

Перевод 7.5.1.3 pointers/ref

---

examples/custom_types/enum/enum_use/input.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rurust/rust-by-example-ru/30)

микро перевод "and" на "и"

---

examples/generics/generics.rs
examples/generics/input.md
examples/structure.json

Небольшой прогресс по #1 
Открыт к предложениям по улучшению переворда, если таковые появятся :construction_worker_man:

Добавлен перевод Generics

---

examples/scope/lifetime/methods/input.md
examples/scope/lifetime/methods/methods.rs
examples/scope/lifetime/struct/input.md
examples/scope/lifetime/struct/struct.rs
examples/structure.json

Перевод небольшой части.
Слово "Аннотации" точно подходит по смыслу ?
И ничего, если случайно vim автоматически строку перенес ?

Перевод Lifetime (13.4.3 | 13.4.4)

---

examples/scope/lifetime/lifetime_bounds/bounds.rs
examples/scope/lifetime/struct/struct.rs
examples/trait/clone/clone.rs
examples/trait/derive/derive.rs
examples/trait/drop/drop.rs
examples/trait/ops/operator.rs

Перевел примеры в предыдущих ПР 🌀

Перевод примеров в println!

---

src/mod.md
src/mod/split.md
src/mod/struct_visibility.md
src/mod/super.md
src/mod/use.md
src/mod/visibility.md

Перевод modules

---

src/crates.md
src/crates/lib.md
src/crates/link.md

Перевод Crates

---

src/generics.md
src/generics/bounds.md
src/generics/bounds/testcase_empty.md
src/generics/gen_fn.md
src/generics/gen_trait.md
src/generics/impl.md
src/generics/multi_bounds.md
src/generics/where.md

Перевод Generics

---

src/std_misc.md
src/std_misc/threads.md

Перевод std misc

---

src/std.md
src/std/box.md
src/std/option.md
src/std/panic.md
src/std/vec.md

Перевод std library types

---

.travis.yml

Подготовка к заливке в мастер ветку mdbook

---

.travis.yml

ветку `ru-version` можно удалять

change CI build

---

.travis.yml

Исправление сборки для правильного рендеринга

---

.travis.yml

fix issue #120

---

.travis.yml

Reverts ruRust/rust-by-example-ru#122

Revert "fix issue 120"

---

src/SUMMARY.md

Обновление SUMMARY

---

src/conversion.md

translate conversion.md
